### ISSUE TITLE
listkeys error

### ISSUE THREAD

**Issue by canfeit** [joyent/sdc-cloudapi#10]
```
After CreateKey or DeleteKey operation,for more than 10 seconds,sdc-listkeys results are repeated in between old and new data.
```

$ triton key ls
FINGERPRINT                                      NAME
6f:f8:c7:......:e1:03:cd  initial-key

wangjh@wangjh-BCC-PC MINGW32 /c/Users/wangjh
$ triton key add --name=test ~/.ssh/github_rsa.pub
Added key "test" 

> (20:40:a7:......:e1:3c:b4)

wangjh@wangjh-BCC-PC MINGW32 /c/Users/wangjh
$ triton key ls
FINGERPRINT                                      NAME
6f:f8:c7:......:e1:03:cd  initial-key
20:40:a7:......:e1:3c:b4  test

wangjh@wangjh-BCC-PC MINGW32 /c/Users/wangjh
$ triton key ls
FINGERPRINT                                      NAME
6f:f8:c7:......:e1:03:cd  initial-key

wangjh@wangjh-BCC-PC MINGW32 /c/Users/wangjh
$ triton key ls
FINGERPRINT                                      NAME
6f:f8:c7:......:e1:03:cd  initial-key
20:40:a7:......:e1:3c:b4  test

wangjh@wangjh-BCC-PC MINGW32 /c/Users/wangjh
$ triton key ls
FINGERPRINT                                      NAME
6f:f8:c7:......:e1:03:cd  initial-key
20:40:a7:......:e1:3c:b4  test

wangjh@wangjh-BCC-PC MINGW32 /c/Users/wangjh
$ triton key ls
FINGERPRINT                                      NAME
6f:f8:c7:......:e1:03:cd  initial-key

wangjh@wangjh-BCC-PC MINGW32 /c/Users/wangjh
$ triton key ls
FINGERPRINT                                      NAME
6f:f8:c7:......:e1:03:cd  initial-key
20:40:a7:......:e1:3c:b4  test

wangjh@wangjh-BCC-PC MINGW32 /c/Users/wangjh
$ triton key ls
FINGERPRINT                                      NAME
6f:f8:c7:......:e1:03:cd  initial-key

This problem exists in node-triton CLI、node-smartdc CLI and CloudAPI.

**Comment by tgross** [comment]
@canfeit I'm not an expert in this subsystem but it's my understanding that you probably hit [mahi](https://github.com/joyent/mahi) caching. This issue has been open a while without further comment though, so for the time being I'm going to close this GitHub issue and refer you to [the mailing list or IRC](https://github.com/joyent/triton#community) if you have more questions.
