### ISSUE TITLE
Instance resize fails with differing traits error

### ISSUE THREAD

**Issue by Smithx10** [joyent/sdc-cloudapi#34]
```
arch@9d46dd2d-1178-ce83-cbc4-d396e4a24060 /g/sdc-cloudapi ❯❯❯ tt inst resize thatch c5f53a16-6e7b-4827-bf1f-9bf1244f5df3                                           changefeed ✭ ✱
Resizing instance thatch to "c5f53a16-6e7b-4827-bf1f-9bf1244f5df3"
triton instance resize: error (InvalidArgument): Resizing to package with differing traits not supported
```

Seem's like CloudAPI tries to do the following (https://github.com/joyent/sdc-cloudapi/blob/master/lib/machines.js#L2150) 
```
 if (!jsprim.deepEqual(req.pkg.traits, req.machine.package.traits)) {
```

But req.machine.package.traits is undefined.

I believe this is because in tranlsate()  we are returning packages[0].name instead of the package object.  (https://github.com/joyent/sdc-cloudapi/blob/master/lib/machines.js#L241)
```
        msg.package = packages[0] ? packages[0].name : '';
```

When I changed it to the following it worked.
```
        msg.package = packages[0] ? packages[0] : '';
```

_edit_ :

I had to warp that in a conditional so that it doesn't break Client Libraries.  The Trition Client Libraries may depend on package being a string and not a object.

```
        if (req.params.action === 'resize') {
            msg.package = packages[0] ? packages[0] : '';
        }
```

**Comment by twhiteman** [comment]
Thanks for the report - this should be fixed with commit a6876b6.
